# -*- coding: utf-8 -*-
"""Evaluate_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZWjqIc967Pw5YeCyRHWBrMdKAW4LJjvq

# **Model Evaluation and Conversion to TensorFlow Lite**

This notebook focuses on evaluating the performance of the model on  test dataset and converting it to TensorFlow Lite (TFLite) format. The TFLite format is optimized for inference on mobile and edge devices, making it ideal for deployment in resource-constrained environments.
"""

# Commented out IPython magic to ensure Python compatibility.
# %run -i Training.ipynb

"""### **Importing necessary libraries**"""

import os

"""### **Model Evaluation on Test Data**"""

model_test=model.evaluate(test_ds)

"""### **Make a directory to save the model**"""

os.mkdir('saved_models')

"""### **Conversion and Saving of TensorFlow Lite Model**"""

# Convert the model to TensorFlow Lite format
converter = tf.lite.TFLiteConverter.from_keras_model(model)
tflite_model = converter.convert()

# Save the TensorFlow Lite model to file
with open('/content/saved_models/Food_ingredients_classifier.tflite', 'wb') as f:
    f.write(tflite_model)